guests:
- name: bastion
  type: bastion
  cpu: 1
  mem: 8192
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 35g
  disk_data_size: 200g
- name: master01
  type: master
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 35g
  disk_data_size: 80g
- name: infranode01
  type: infra
  cpu: 1
  mem: 8192
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 35g
  disk_data_size: 80g
- name: node01
  type: node
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 35g
  disk_data_size: 80g
- name: node02
  type: node
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 35g
  disk_data_size: 80g
- name: node03
  type: node
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 35g
  disk_data_size: 80g