guests:
- name: bastion
  cpu: 1
  mem: 8192
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 40g
  disk_data_size: 200g
- name: master01
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 40g
  disk_data_size: 100g
- name: infranode01
  cpu: 1
  mem: 8192
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 40g
  disk_data_size: 100g
- name: node01
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 40g
  disk_data_size: 100g
- name: node02
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 40g
  disk_data_size: 100g
- name: node03
  cpu: 1
  mem: 16384
  virt_type: kvm
  virt_hypervisor: hvm
  network: bridge=virbr0
  os_type: linux
  os_variant: rhel7.5
  disk_os_size: 40g
  disk_data_size: 100g